# Generated by Django 5.1.1 on 2024-09-27 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('ktc_player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=255)),
                ('sleeper_player_id', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('position', models.CharField(blank=True, max_length=32, null=True)),
                ('experience', models.CharField(blank=True, max_length=32, null=True)),
                ('team', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KtcPlayerValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ktc_value', models.IntegerField(db_column='ktc_value')),
                ('date', models.DateField(db_column='date')),
                ('ktc_player_id', models.ForeignKey(db_column='ktc_player_id', on_delete=django.db.models.deletion.CASCADE, to='fantasy_trades_app.players')),
            ],
            options={
                'unique_together': {('ktc_player_id', 'date')},
            },
        ),
    ]
