# Generated by Django 5.1.1 on 2024-09-27 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('ktc_player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=255)),
                ('sleeper_player_id', models.IntegerField(null=True, blank=True)),
                ('age', models.IntegerField( null=True, blank=True)),
                ('number', models.IntegerField(null=True, blank=True)),
                ('position', models.CharField(max_length=32, null=True, blank=True)),
                ('experience', models.CharField(max_length=32, null=True, blank=True)),
                ('team', models.CharField(max_length=255, null=True, blank=True))
            ],
        ),
        migrations.CreateModel(
            name='KtcPlayerValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ktc_value', models.IntegerField()),
                ('date', models.DateField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy_trades_app.players')),
            ],
            options={
                'unique_together': {('player', 'date')},
            },
        ),
    ]
