# Generated by Django 5.1.3 on 2024-11-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy_trades_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
