
services:
  db:
    image: postgres:latest
    container_name: fantasy_trades_db
    environment:
      POSTGRES_DB: fantasy_trades_db
      POSTGRES_USER: fantasy_trades_appuser
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
#    restart: always

  web:
    container_name: fantasy_trades_app
    image: fantasy_trades_app_django
    build: .
    volumes:
      - .:/app
      - ../migration_data/ktc_player_data:/app/migration_data/ktc_player_data
      - ../migration_data/sleeper_data:/app/migration_data/sleeper_data
    ports:
      - "8000:8000"
#    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DJANGO_DB_HOST: db
      DJANGO_DB_NAME: fantasy_trades_db
      DJANGO_DB_USER: fantasy_trades_appuser
      DJANGO_DB_PASSWORD: ${POSTGRES_PASSWORD}

networks:
    fantasy_trades_net:
        driver: bridge

volumes:
  postgres_data:
